### PR TITLE
ci: use Github actions

### PR DESCRIPTION
**Pull request by lovesegfault**
This is a best-effort attempt at porting the CI to use GitHub actions. I expect this to be incomplete still and am looking for feedback to improve it.

cc. @grahamc

### CODE REVIEW

**Comment by curiousleo** [comment]
Hi @lovesegfault, thanks for your contribution! Did you discuss this change with @grahamc?

My first take:
- `-350 +79` is a great change: the current build setup is clearly more complex than it needs to be.
- Building CI with nix using a pinned nixpkgs ([see here](https://github.com/target/lorri/blob/master/nix/update-dependencies.sh#L7-L9)) has the big advantage that we know lorri will build for that channel (nixos-19.09 currently). For example, we know that lorri will build against the Rust version shipped in that nixpkgs channel. Nixpkgs is the main way lorri is distributed right now, so this matters. In the GitHub CI action, it is not clear to me which Rust version is actually used.

**Comment by Profpatsch** [comment]
I don’t know whether we can enable Github actions here in the first place, since `target` probably has strict rules on what CI is allowed for its repositories.

**Comment by Profpatsch** [comment]
Can you resurrect the travis files? I’d like to have both in parallel to see if github actions bring an improvement. Also, like mentioned above, to see whether github actions are enabled in the target orga in the first place.

**Comment by Profpatsch** [comment]
Gonna merge and see whether it does something.

**Pull request merged**
