### PR TITLE
Subcommands cleanup

### PR DESCRIPTION
**Pull request by curiousleo**
# Overview

Just a little cleanup before we go to 1.0.

See https://github.com/target/lorri/pull/317/commits/84fa27579ef79c1ec3e04b4ba42ac229a7c5422d commit message.

## Checklist

- [x] Updated the documentation (code documentation, command help, ...)
- [ ] Tested the change (unit or integration tests)
- [x] Amended the changelog in `release.nix` (see `release.nix` for instructions)

### CODE REVIEW

**Comment by curiousleo** [comment]
> I'm going to do a quick look to see if there are methods built in to structopt to "hide" or "demote" some subcommands, but if you don't hear from me merge away :P

Something like `#[structopt(raw(hidden = true))]` might work. I'll give it a try.

https://docs.rs/structopt/0.3.8/structopt/#raw-methods
https://docs.rs/clap/2.33.0/clap/struct.Arg.html#method.hidden
Example: https://github.com/TeXitoi/structopt/issues/93

**Comment by grahamc** [comment]
I cracked it!

```diff
diff --git a/src/cli.rs b/src/cli.rs
index df639f6..36675ac 100644
--- a/src/cli.rs
+++ b/src/cli.rs
@@ -34,7 +34,7 @@ pub enum Command {
     Shell(ShellOptions),

     /// (internal) Used internally by `lorri shell`
-    #[structopt(name = "zz_start_user_shell")]
+    #[structopt(name = "zz_start_user_shell", raw(setting = "structopt::clap::AppSettings::Hidden"))]
     StartUserShell_(StartUserShellOptions_),

     /// Build project whenever an input file changes
@@ -46,7 +46,7 @@ pub enum Command {
     Daemon,

     /// (internal) Tell the lorri daemon to care about the current directory's project
-    #[structopt(name = "zz_ping")]
+    #[structopt(name = "zz_ping", raw(setting = "structopt::clap::AppSettings::Hidden"))]
     Ping_(Ping_),

     /// Upgrade lorri
```

maybe with this we can rename `zz_` to `internal_api_`  or `private_api_` to make callers painfully aware?

**Comment by grahamc** [comment]
The trick was going back in time to the docs for the version of structopts we use: https://docs.rs/structopt/0.2.18/structopt/ and playing with the `raw` format there.

**Comment by curiousleo** [comment]
> The trick was going back in time to the docs for the version of structopts we use: https://docs.rs/structopt/0.2.18/structopt/ and playing with the `raw` format there.

_Nice_

**Pull request merged**
