### PR TITLE
chore(CI): remove travis CI

### PR DESCRIPTION
**Pull request by Profpatsch**
Thanks to the awesome work by @cole-h, we can remove Travis.

### CODE REVIEW

**Comment by Profpatsch** [comment]
I already turned off the auto-builds in the travis settings and removed the cachix secret.

**Comment by curiousleo** [comment]
Would you like to introduce a naming scheme for commits (`chore/feat/...`)? I'm in favour. I think that `CONTRIBUTING.md` would be a good place to explain the scheme.

**Comment by Profpatsch** [comment]
Maybe? I don’t want to force people to use it, I just think it’s neat.

**Comment by cole-h** [comment]
Happy to be of assistance!

I can't help but notice that we don't have any darwin build steps (while Travis did) -- was this a conscious decision? If not, I could update my old branch and PR it.

**Comment by curiousleo** [comment]
> I can't help but notice that we don't have any darwin build steps (while Travis did) -- was this a conscious decision? If not, I could update my old branch and PR it.

Great catch @cole-h -- a PR that adds macOS to the GitHub actions CI would be very much appreciated!

**Comment by cole-h** [comment]
My plan is to get that done tomorrow.

**Comment by cole-h** [comment]
Done in https://github.com/target/lorri/pull/442.

**Pull request merged**
