### PR TITLE
readme -> add note about cachix

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by Profpatsch** [comment]
Did you have to rebuild many dependencies to install lorri?

**Comment by srghma** [comment]
dont remember exactly, it downloaded all rust libs (already built, this is 100%), but dont remember did it download lorri itself or built it

**Comment by Profpatsch** [comment]
It usually builds lorri, but that shouldn’t take more than a few minutes.

The problem I have with `cachix use` is that it re-writes your `/etc/nix/nix.conf`, which is fine on CI machines but you need `sudo` on normal machines. Plus it doesn’t work on nixos at (at least conceptually).

**Comment by srghma** [comment]
for me it added info to /home/srghma/.config/nix/nix.conf, then I copied that new info and added to 

```
    binaryCaches = [
      "https://all-hies.cachix.org"
      "https://cache.nixos.org"
      "https://cachix.cachix.org"
      "https://srghma.cachix.org"
      "https://hie-nix.cachix.org"
      "https://nixcache.reflex-frp.org"
      "https://hydra.iohk.io"
      "https://lorri-test.cachix.org"
    ];

    binaryCachePublicKeys = [
      "all-hies.cachix.org-1:JjrzAOEUsD9ZMt8fdFbzo3jNAyEWlPAwdVuHw4RD43k="
      "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
      "cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM="
      "srghma.cachix.org-1:EUHKjTh/WKs49hFtw6bwDE9oQLeX5afml0cAKc97MbI="
      "hie-nix.cachix.org-1:EjBSHzF6VmDnzqlldGXbi0RM3HdjfTU3yDRi9Pd0jTY="
      "ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI="
      "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="
      "lorri-test.cachix.org-1:wZCd/aYaK5pMR0odlnNIdinNTR+3mz3A60NYlFiCeO0="
    ];

```

**Comment by Profpatsch** [comment]
I’m gonna close this, because lorri is in nixpkgs now, and people who want to build from master can wait for a few mins I guess.

**Pull request closed without merging**
