### PR TITLE
src/nix,builder: return more descriptive error if nix not in PATH

### PR DESCRIPTION
**Pull request by Profpatsch**

### CODE REVIEW

**Comment by Profpatsch** [comment]
This has to be rebased onto the new `execute` function in `builder.nix`.

**Comment by grahamc** [comment]
Looks good post rebase.

**Comment by Profpatsch** [comment]
I opened https://github.com/rust-lang/rust/issues/65968 so maybe we can get rid of enums like this in the future.

**Comment by Profpatsch** [comment]
@grahamc I had to introduce two error wrappers when rebasing onto the new code, PTAL.

**Pull request merged**
