### PR TITLE
fix(build_loop.rs): don't build a project twice if there are several …

### LINKED ISSUE #464: Spurious rebuilds when watched file changes during compilation
**Describe the bug**

If two watched files change during a projet is built, then the project will be rebuilt twice once the build completes.
I intend to open a PR later today fixing this.

**To Reproduce**

Create a folder `a` and `shell.nix` as follows:
```nix
let
  pkgs = import <nixpkgs> {};
  dep = pkgs.stdenv.mkDerivation {
    name = "dep";
    src = ./a;
    buildPhase = ''
      sleep 20
    '';
    installPhase = ''
      touch $out
    '';
  };
in
  pkgs.mkShell {
    buildInputs = [ dep ];
  }
```

trigger a recompilation: `date > a/a`
Then during the build (which takes 20 secs):
`date > a/b; sleep 2; date > a/c`
In the log, observe how once the current build complete, the build it started twice.

**Expected behavior**
Any number of events during the initial build should only trigger one build.

**Metadata**

```console
$  lorri info --shell-file shell.nix 
lorri version: 1.1
GC roots exist, shell_gc_root: "/home/symphorien/.cache/lorri/gc_roots/90c4ac62ff5ef60472c76eeb4f573f86/gc_root/shell_gc_root"
```

```console
$  uname -a
Linux nlaptop 5.7.11 #1-NixOS SMP Wed Jul 29 08:20:01 UTC 2020 x86_64 G
```

### PR DESCRIPTION
**Pull request by symphorien**
Closes #464.

## Overview

Before starting a build, drain all events which would start the same build.

## Checklist

- [ ] Updated the documentation (code documentation, command help, ...)
- [ ] Tested the change (unit or integration tests)
- [ ] Amended the changelog in `release.nix` (see `release.nix` for instructions)

### CODE REVIEW

**Comment by symphorien** [comment]
bump

**Comment by voobscout** [comment]
also very interested in getting it merged

**Comment by takeda** [comment]
I'm also interested in merging this.

Looks like development might continue here: https://github.com/nix-community/lorri

**Comment by symphorien** [comment]
reopened as https://github.com/nix-community/lorri/pull/3

**Comment by Profpatsch** [comment]
Fixed in https://github.com/nix-community/lorri/pull/7 and released as 1.3.0 in nixpkgs unstable.

**Pull request closed without merging**
