### PR TITLE
trivial-shell.nix: use with

### PR DESCRIPTION
**Pull request by asymmetric**
To clean up list of packages.

I'm assuming this should not be mentioned in the release notes, since it's a visible and backwards-compatible change with no effect on lorri's semantics, but let me know if it should instead.

## Checklist

- [ ] Updated the documentation (code documentation, command help, ...)
- [ ] Tested the change (unit or integration tests)
- [ ] Amended the changelog in `release.nix` (see `release.nix` for instructions)

### CODE REVIEW

**Comment by asymmetric** [comment]
I agree with you @curiousleo, `with` can easily be abused. But I think that used this way, on the RHS of an assignment, limits its nastier aspects. :)

**Comment by curiousleo** [comment]
@Profpatsch @grahamc @nyarly a second reviewer's opinion perhaps?

**Comment by Profpatsch** [comment]
yeah, sorry, I’m gonna -1 this one, I manually prefixed `pkgs` as a deliberate choice, because I don’t think a file like this should contain an advanced language feature (and frankly an anti-pattern) like `with`.

**Comment by Profpatsch** [comment]
But thank you @asymmetric for your PR, we have a bunch of issues marked as good first issues if you want to take a shot.

**Pull request closed without merging**
