### PR TITLE
Add CI badge to README

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@Profpatsch @curiousleo @cole-h please review

**Comment by curiousleo** [comment]
@Profpatsch @cole-h is GitHub Actions the "official" CI now?

**Comment by cole-h** [comment]
Not yet, I don't think. We don't have total feature parity (read: macOS build steps). We know it's at least feasible (see: https://github.com/target/lorri/pull/402), but once https://github.com/target/lorri/pull/411 is deemed satisfactory (and thus merged), it should be possible to come back and add macOS and get *that* merged -- unless anybody has any objections to the way that comes about.

**Comment by Profpatsch** [comment]
I have never understood the idea behind these, but I won’t block merging the badge.

**Comment by gliptak** [comment]
@Profpatsch I look at the build badge in particular and badges of other code quality tooling as indicators of project health

**Comment by Profpatsch** [comment]
Let’s add a static image to a green badge then :)

**Pull request merged**
