### PR TITLE
Setup direnv in emacs: Add emacs-racer config

### PR DESCRIPTION
**Pull request by Jeschli**

### CODE REVIEW

**Comment by curiousleo** [comment]
Hey, thanks for contributing this config! Sorry I messed up this PR by moving documentation around. The new place for this would be https://github.com/target/lorri/blob/master/contrib/emacs.md.

**Comment by Jeschli** [comment]
@curiousleo changed to emacs.md

**Comment by curiousleo** [comment]
LGTM!

**Comment by Jeschli** [comment]
Not sure what went wrong with the CI pipeline.

**Pull request merged**
